version: '3.3'
services:
      propaganda:
        build:
          context: .
          args:
            consKey: ""
            consSec: ""
            accToken: ""
            accTokenSec: ""

        ports: 
            # change only the first (external) port, internal doesn't matter
          - "80:80"
        restart: unless-stopped